FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish --no-restore


FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime

WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://0.0.0.0:26761
ENV DOTNET_EnableDiagnostics=0

EXPOSE 26761

USER app

ENTRYPOINT ["dotnet", "ArcadeBridgeRelay.dll"]
